// <auto-generated />
namespace March_Madness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakePoolOwnerAddressRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakePoolOwnerAddressRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201803102340115_Make PoolOwner Address Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
