// <auto-generated />
namespace March_Madness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialMigrationafterresetbecauseoferrorswithGamePickForeingKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialMigrationafterresetbecauseoferrorswithGamePickForeingKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201802252016025_Initial Migration after reset because of errors with GamePick Foreing Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
