// <auto-generated />
namespace March_Madness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakingBracketEntriesbelongtoasinglepool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakingBracketEntriesbelongtoasinglepool));
        
        string IMigrationMetadata.Id
        {
            get { return "201803100358481_Making BracketEntries belong to a single pool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
