// <auto-generated />
namespace March_Madness.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HopefullygettingridofTournamentEntryIDforBracketEntry_idinmodeltomatchcurrentstateofDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HopefullygettingridofTournamentEntryIDforBracketEntry_idinmodeltomatchcurrentstateofDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201803100534319_Hopefully getting rid of TournamentEntryID for BracketEntry_id in model to match current state of DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
